---
title: "Kérdőív generálás v1"
output:
  html_notebook: default
  pdf_document: default
---


## import packages

```{r}
library(idefix)
```

```{r Setting up profile, and }
set.seed(123)
cs <- Profiles(lvls = c(3, 3, 3), coding = c("D", "D", "D")) #dummy coded profiles

m <- c(0.25, 0.5, 1, -0.5, -1, 0.5)
v <- diag(length(m))
ps <- MASS::mvrnorm(n = 500, mu = m, Sigma = v)
init.des <- Modfed(cand.set = cs, n.sets = 8, n.alts = 2, alt.cte = c(0, 0), par.draws = ps)$design #n.sets - number of choice sets, nalts - number of alternatives, alt.cte - alternative specific constant

init.des
```

```{r Seeting }
coded <- c("D", "D", "D") # Coding.
# Levels as they should appear in survey.
al <- list(
c("200 Ft", "500 Ft", "1000 Ft"), # Levels attribute 1.
c("2 min", "15 min", "30 min"), # Levels attribute 2.
c("bad", "moderate", "good") # Levels attribute 3.
)
# Decode
DD <- Decode(des = init.des, n.alts = 2, lvl.names = al, coding = coded)
DD
```




```{r Simulating choice data for the initial design}
 truePREF <- c(0.5, 1, 2, -1, -1, 1.5) #assumed true preferences of 
 set.seed(123)
 y.sim <- RespondMNL(par = truePREF, des = init.des, n.alts = 2)
 y.sim
```

```{r Sampleing from the posterior distribution}
draws <- ImpsampMNL(n.draws = 200, prior.mean = m,prior.covar = v, des = init.des, n.alts = 2, y = y.sim)
draws
```

```{r Selecting the next optimal choice set}
set <- SeqMOD(des = init.des, cand.set = cs, n.alts = 2, par.draws = draws$sample, prior.covar = v, weights = draws$weights)
set
```

```{r}
y.sim <- RespondMNL(par = truePREF, des = set$set, n.alts = 2)
y.sim
```

```{r }
levels <- c(3, 3)
p.mean <- c(0.3, 0.7, 0.3, 0.7)
low = c(-Inf, -Inf, -Inf, 0) #truncated normal distribution
up = rep(Inf, length(p.mean))
p.var <- diag(length(p.mean)) 
code <- c("D", "D")
cand <- Profiles(lvls = levels, coding = code)
n.sets <- 8

# settings of the survey
alternatives <- c("A alternatíva", "B alternatíva")
attributes <- c("Ár", "Idő", "Zsúfoltság")
attributes <- c("Ár", "Idő")
labels <- vector(mode="list", length(attributes))
labels[[1]] <- c("300 Ft", "600 Ft", "900 Ft")
labels[[2]] <- c("30 perc", "18 perc", "6 perc")
labels[[3]] <- c("Van ülőhely", "Nincs ülőhely, de állóhely van", "Kevés állóhely van")
i.text <- "Welcome, here are some instructions ... good luck!"
b.text <- "Please choose the alternative you prefer"
e.text <- "Thanks for taking the survey"
dataDir <- getwd()
# Display the survey 
SurveyApp(des = NULL, n.total = n.sets, alts = alternatives,
          atts = attributes, lvl.names = labels, coding = code, 
          buttons.text = b.text, intro.text = i.text, end.text = e.text, 
          prior.mean = p.mean, prior.covar = p.var, cand.set = cand, 
          lower = low, upper = up, n.draws = 50, data.dir = "./results")

```
```{r Nem adaptív set}
data("example_design", package = "idefix")
xdes <- example_design

alternatives <- c("A alternatíva", "B alternatíva")
attributes <- c("Ár", "Idő", "Zsúfoltság")

code <- c("D", "D", "D")

labels <- vector(mode="list", length(attributes))
labels[[1]] <- c("300 Ft", "600 Ft", "900 Ft")
labels[[2]] <- c("30 perc", "18 perc", "6 perc")
labels[[3]] <- c("Van ülőhely", "Nincs ülőhely, de állóhely van", "Kevés állóhely van")
i.text <- "Welcome, here are some instructions ... good luck!"
b.text <- "Please choose the alternative you prefer"
e.text <- "Thanks for taking the survey"
dataDir <- getwd()

 SurveyApp(des = xdes, n.total = n.sets, alts = alternatives, 
           atts = attributes, lvl.names = labels, coding = code,
buttons.text = b.text, intro.text = i.text, end.text = e.text,
data.dir = NULL)
```

